title: jongho-inside
description: >-
  C/C++ (ROS)
  System Simulation
  - AnyLogic, AutoMod
  AMHS Simulation Anaylist
url: "https://jonghoinside.github.io"
github: jonghoinside
email: jonghoinside@gmail.com
# google_analytics: UA-146771648-1

exclude: [README.md, Gemfile, Gemfile.lock]

comment:
  provider: disqus

disaus:
  shortname: https-jonghoinside-github-io

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
